### ISSUE TITLE
Reports invalid (as 'not in use') VAT numbers as valid

### ISSUE THREAD

**Issue by mpeltonen** [adriantombu/vat-number#36]
checkVatAsync *does not* necessarily throw exception when given VAT number is invalid, so this lib currently reports invalid numbers as valid.

Change the number in 'a wrong vat number should return an error message' test to the invalid example in README, and the test fails.

Validity of the number should not be hard-coded to true in 'no exception' case, but should also be taken from the result object.

**Comment by adriantombu** [comment]
Hey @mpeltonen ! Thanks for taking the time to report that bug, I don't even know how I missed something so obvious in the first place 😳

I pushed the fix, it's already available on [NPM](https://www.npmjs.com/package/@adriantombu/vat-number) 😊

**Comment by mpeltonen** [comment]
Thanks for a quick fix and release!
